[package]
name = "baggage"
version = "0.1.0"
authors = ["jspspike <jspspike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
